name: PSP
on:
  pull_request:
  workflow_dispatch:

jobs:
  build:
    name: Percona Postgres
    strategy:
      matrix:
        ubuntu_version: [22]
        build_type: [debug,debugoptimized]
        build_script: [make, meson]
    runs-on: ubuntu-${{ matrix.ubuntu_version }}.04
    steps:

      - name: Clone repository
        uses: actions/checkout@v4
        with:
          path: 'src'
          submodules: recursive
          ref: ${{ github.ref }}

      - name: Install dependencies
        run: src/.scripts/ubuntu-deps.sh

      - name: Setup kmip and vault
        run: src/.scripts/setup-keyring-servers.sh

      - name: Build and test postgres
        run: src/.scripts/${{ matrix.build_script }}-build.sh ${{ matrix.build_type }}

      - name: Test postgres
        run: src/.scripts/${{ matrix.build_script }}-test.sh

      - name: Report on test fail
        uses: actions/upload-artifact@v4
        if: ${{ failure() }}
        with:
          name: testlog-ubuntu-${{ matrix.ubuntu_version }}.04-meson-${{ matrix.build_type }}
          path: |
            src/build/testrun/
          retention-days: 3
