name: Sanitizers
on:
  pull_request:
    paths-ignore:
      - contrib/pg_tde/documentation/**
  push:
    branches:
      - TDE_REL_17_STABLE
    paths-ignore:
      - contrib/pg_tde/documentation/**

env:
  CC: clang
  LD: clang
  UBSAN_OPTIONS: log_path=${{ github.workspace }}/sanitize.log print_suppressions=0 print_stacktrace=1 print_summary=1 halt_on_error=1
  ASAN_OPTIONS: log_path=${{ github.workspace }}/sanitize.log print_suppressions=0 abort_on_error=1
  LSAN_OPTIONS: log_path=${{ github.workspace }}/sanitize.log print_suppressions=0 suppressions=${{ github.workspace }}/ci_scripts/suppressions/lsan.supp
  ASAN_SYMBOLIZER_PATH: /usr/bin/llvm-symbolizer-14
  EXTRA_REGRESS_OPTS: "--temp-config=${{ github.workspace }}/test_postgresql.conf"
  PGCTLTIMEOUT: 120

jobs:
  run:
    name: Run
    runs-on: ubuntu-22.04
    steps:
      - name: Clone repository
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Install dependencies
        run: ci_scripts/ubuntu-deps.sh

      - name: Build postgres
        run: ci_scripts/make-build.sh sanitize

      - name: Setup kmip and vault
        run: ci_scripts/setup-keyring-servers.sh

      - name: Configure test postgres
        run: echo 'max_stack_depth=8MB' > test_postgresql.conf

      - name: Run tests pg_tde tests
        run: ci_scripts/make-test.sh tde

      - name: Run PG regression tests
        run: ci_scripts/make-test.sh server

      - name: Print sanitize logs
        if: ${{ !cancelled() }}
        run: cat sanitize.log.*

      - name: Report on test fail
        uses: actions/upload-artifact@v4
        if: ${{ failure() }}
        with:
          name: sanitizers-testlog
          path: |
            build/testrun
            contrib/**/log
            contrib/**/regression.diffs
            contrib/**/regression.out
            contrib/**/results
            contrib/**/tmp_check
            contrib/**/t/results
            src/test/**/log
            src/test/**/regression.diffs
            src/test/**/regression.out
            src/test/**/results
            src/test/**/tmp_check
            sanitize.log.*
          retention-days: 3
